<?php
return array(
	/* 系统设置  */
	'SAVE_LOG_OPEN' => array(
		'name'    => '操作日志记录',
		'group'   => '系统设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'panelHeight'=>'auto','data'=>array(array('text'=>'开启', 'value'=>'开启'),array('text'=>'关闭', 'value'=>'关闭')))),
		'default' => C('SAVE_LOG_OPEN'),
		'dict'    => array('开启' => 1, '关闭' => 0),
	),
	'LOGIN_ONLY_ONE' => array(
		'name'    => '单设备登录',
		'group'   => '系统设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'panelHeight'=>'auto','data'=>array(array('text'=>'开启', 'value'=>'开启'),array('text'=>'关闭', 'value'=>'关闭')))),
		'default' => C('LOGIN_ONLY_ONE'),
		'dict'    => array('开启' => 1, '关闭' => 0),
	),
	'MAX_LOGIN_TIMES' => array(
		'name'    => '登录失败后次数限制',
		'group'   => '系统设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1, 'max'=>20)),
		'default' => C('MAX_LOGIN_TIMES'),
	),
	'LOGIN_WAIT_TIME' => array(
		'name'    => '错误等待时间(分钟)',
		'group'   => '系统设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1)),
		'default' => C('LOGIN_WAIT_TIME'),
	),
	'CATEGORY_LEVEL' => array(
		'name'    => '栏目管理级别数',
		'group'   => '系统设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>2, 'max'=>10)),
		'default' => C('CATEGORY_LEVEL'),
	),
	'API_SIGN' => array(
		'name'    => '接口签名',
		'group'   => '系统设置',
		'editor'  => 'text',
		'default' => C('API_SIGN'),
	),
	
	/* 上传设置  */
	'FILE_UPLOAD_CONFIG.exts' => array(
		'name'    => '允许上传扩展(默认)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'multiple'=>true,'data'=>array(
			array('text'=>'png', 'value'=>'png'),
			array('text'=>'jpg', 'value'=>'jpg'),
			array('text'=>'jpeg', 'value'=>'jpeg'),
			array('text'=>'gif', 'value'=>'gif'),
			array('text'=>'bmp', 'value'=>'bmp'),
			array('text'=>'flv', 'value'=>'flv'),
			array('text'=>'swf', 'value'=>'swf'),
			array('text'=>'mkv', 'value'=>'mkv'),
			array('text'=>'avi', 'value'=>'avi'),
			array('text'=>'rm', 'value'=>'rm'),
			array('text'=>'rmvb', 'value'=>'rmvb'),
			array('text'=>'mpeg', 'value'=>'mpeg'),
			array('text'=>'mpg', 'value'=>'mpg'),
			array('text'=>'ogg', 'value'=>'ogg'),
			array('text'=>'ogv', 'value'=>'ogv'),
			array('text'=>'mov', 'value'=>'mov'),
			array('text'=>'wmv', 'value'=>'wmv'),
			array('text'=>'mp4', 'value'=>'mp4'),
			array('text'=>'webm', 'value'=>'webm'),
			array('text'=>'mp3', 'value'=>'mp3'),
			array('text'=>'wav', 'value'=>'wav'),
			array('text'=>'mid', 'value'=>'mid'),
			array('text'=>'rar', 'value'=>'rar'),
			array('text'=>'zip', 'value'=>'zip'),
			array('text'=>'tar', 'value'=>'tar'),
			array('text'=>'gz', 'value'=>'gz'),
			array('text'=>'7z', 'value'=>'7z'),
			array('text'=>'bz2', 'value'=>'bz2'),
			array('text'=>'cab', 'value'=>'cab'),
			array('text'=>'iso', 'value'=>'iso'),
			array('text'=>'doc', 'value'=>'doc'),
			array('text'=>'docx', 'value'=>'docx'),
			array('text'=>'xls', 'value'=>'xls'),
			array('text'=>'xlsx', 'value'=>'xlsx'),
			array('text'=>'ppt', 'value'=>'ppt'),
			array('text'=>'pptx', 'value'=>'pptx'),
			array('text'=>'pdf', 'value'=>'pdf'),
			array('text'=>'txt', 'value'=>'txt'),
			array('text'=>'md', 'value'=>'md'),
			array('text'=>'xml', 'value'=>'xml'),
		))),
		'default' => implode(',', C('FILE_UPLOAD_CONFIG.exts')),
		'type'    => 'array',
	),
	'FILE_UPLOAD_CONFIG.maxSize' => array(
		'name'    => '允许上传大小(默认)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1)),
		'default' => C('FILE_UPLOAD_CONFIG.maxSize'),
	),
	'FILE_UPLOAD_FILE_CONFIG.exts' => array(
		'name'    => '允许上传扩展(文件)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'multiple'=>true,'data'=>array(
			array('text'=>'png', 'value'=>'png'),
			array('text'=>'jpg', 'value'=>'jpg'),
			array('text'=>'jpeg', 'value'=>'jpeg'),
			array('text'=>'gif', 'value'=>'gif'),
			array('text'=>'bmp', 'value'=>'bmp'),
			array('text'=>'flv', 'value'=>'flv'),
			array('text'=>'swf', 'value'=>'swf'),
			array('text'=>'mkv', 'value'=>'mkv'),
			array('text'=>'avi', 'value'=>'avi'),
			array('text'=>'rm', 'value'=>'rm'),
			array('text'=>'rmvb', 'value'=>'rmvb'),
			array('text'=>'mpeg', 'value'=>'mpeg'),
			array('text'=>'mpg', 'value'=>'mpg'),
			array('text'=>'ogg', 'value'=>'ogg'),
			array('text'=>'ogv', 'value'=>'ogv'),
			array('text'=>'mov', 'value'=>'mov'),
			array('text'=>'wmv', 'value'=>'wmv'),
			array('text'=>'mp4', 'value'=>'mp4'),
			array('text'=>'webm', 'value'=>'webm'),
			array('text'=>'mp3', 'value'=>'mp3'),
			array('text'=>'wav', 'value'=>'wav'),
			array('text'=>'mid', 'value'=>'mid'),
			array('text'=>'rar', 'value'=>'rar'),
			array('text'=>'zip', 'value'=>'zip'),
			array('text'=>'tar', 'value'=>'tar'),
			array('text'=>'gz', 'value'=>'gz'),
			array('text'=>'7z', 'value'=>'7z'),
			array('text'=>'bz2', 'value'=>'bz2'),
			array('text'=>'cab', 'value'=>'cab'),
			array('text'=>'iso', 'value'=>'iso'),
			array('text'=>'doc', 'value'=>'doc'),
			array('text'=>'docx', 'value'=>'docx'),
			array('text'=>'xls', 'value'=>'xls'),
			array('text'=>'xlsx', 'value'=>'xlsx'),
			array('text'=>'ppt', 'value'=>'ppt'),
			array('text'=>'pptx', 'value'=>'pptx'),
			array('text'=>'pdf', 'value'=>'pdf'),
			array('text'=>'txt', 'value'=>'txt'),
			array('text'=>'md', 'value'=>'md'),
			array('text'=>'xml', 'value'=>'xml'),
		))),
		'default' => implode(',', C('FILE_UPLOAD_FILE_CONFIG.exts')),
		'type'    => 'array',
	),
	'FILE_UPLOAD_FILE_CONFIG.maxSize' => array(
		'name'    => '允许上传大小(文件)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1)),
		'default' => C('FILE_UPLOAD_FILE_CONFIG.maxSize'),
	),
	'FILE_UPLOAD_IMG_CONFIG.exts' => array(
		'name'    => '允许上传扩展(图片)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'multiple'=>true,'data'=>array(
			array('text'=>'png', 'value'=>'png'),
			array('text'=>'jpg', 'value'=>'jpg'),
			array('text'=>'jpeg', 'value'=>'jpeg'),
			array('text'=>'gif', 'value'=>'gif'),
			array('text'=>'bmp', 'value'=>'bmp'),
		))),
		'default' => implode(',', C('FILE_UPLOAD_IMG_CONFIG.exts')),
		'type'    => 'array',
	),
	'FILE_UPLOAD_IMG_CONFIG.maxSize' => array(
		'name'    => '允许上传大小(图片)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1)),
		'default' => C('FILE_UPLOAD_IMG_CONFIG.maxSize'),
	),
	'FILE_UPLOAD_VIDEO_CONFIG.exts' => array(
		'name'    => '允许上传扩展(影音)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'multiple'=>true,'data'=>array(
			array('text'=>'flv', 'value'=>'flv'),
			array('text'=>'swf', 'value'=>'swf'),
			array('text'=>'mkv', 'value'=>'mkv'),
			array('text'=>'avi', 'value'=>'avi'),
			array('text'=>'rm', 'value'=>'rm'),
			array('text'=>'rmvb', 'value'=>'rmvb'),
			array('text'=>'mpeg', 'value'=>'mpeg'),
			array('text'=>'mpg', 'value'=>'mpg'),
			array('text'=>'ogg', 'value'=>'ogg'),
			array('text'=>'ogv', 'value'=>'ogv'),
			array('text'=>'mov', 'value'=>'mov'),
			array('text'=>'wmv', 'value'=>'wmv'),
			array('text'=>'mp4', 'value'=>'mp4'),
			array('text'=>'webm', 'value'=>'webm'),
			array('text'=>'mp3', 'value'=>'mp3'),
			array('text'=>'wav', 'value'=>'wav'),
			array('text'=>'mid', 'value'=>'mid'),
		))),
		'default' => implode(',', C('FILE_UPLOAD_VIDEO_CONFIG.exts')),
		'type'    => 'array',
	),
	'FILE_UPLOAD_VIDEO_CONFIG.maxSize' => array(
		'name'    => '允许上传大小(影音)',
		'group'   => '上传设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1)),
		'default' => C('FILE_UPLOAD_VIDEO_CONFIG.maxSize'),
	),

	/* 水印设置 */
	'IMAGE_WATER_CONFIG.status' => array(
		'name'    => '启用状态',
		'group'   => '水印设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'panelHeight'=>'auto','data'=>array(array('text'=>'开启', 'value'=>'开启'),array('text'=>'关闭', 'value'=>'关闭')))),
		'default' => C('IMAGE_WATER_CONFIG.status'),
		'dict'    => array('开启' => 1, '关闭' => 0),
	),
	'IMAGE_WATER_CONFIG.type' => array(
		'name'    => '水印模式',
		'group'   => '水印设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>false, 'panelHeight'=>'auto','data'=>array(array('text'=>'文字水印', 'value'=>'文字水印'),array('text'=>'图片水印', 'value'=>'图片水印')))),
		'default' => C('IMAGE_WATER_CONFIG.type'),
		'dict'    => array('图片水印' => 1, '文字水印' => 0),
	),
	'IMAGE_WATER_CONFIG.text' => array(
		'name'    => '水印文字',
		'group'   => '水印设置',
		'editor'  => 'text',
		'default' => C('IMAGE_WATER_CONFIG.text'),
	),
	'IMAGE_WATER_CONFIG.image' => array(
		'name'    => '水印图片',
		'group'   => '水印设置',
		'editor'  => array('type'=>'image','options'=>array('upload'=>U('Upload/image'), 'multiple'=>false, 'accept'=>'image/jpeg,image/jpg,image/png', 'size'=>C('FILE_UPLOAD_IMG_CONFIG.maxSize') )),
		'default' => '',
	),
	'IMAGE_WATER_CONFIG.position' => array(
		'name'    => '水印位置(九宫格)',
		'group'   => '水印设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1, 'max'=>9)),
		'default' => C('IMAGE_WATER_CONFIG.position'),
	),
	'IMAGE_WATER_CONFIG.x' => array(
		'name'    => 'x轴距离',
		'group'   => '水印设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>-9999, 'max'=>9999)),
		'default' => C('IMAGE_WATER_CONFIG.x'),
	),
	'IMAGE_WATER_CONFIG.y' => array(
		'name'    => 'y轴距离',
		'group'   => '水印设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>-9999, 'max'=>9999)),
		'default' => C('IMAGE_WATER_CONFIG.y'),
	),
	'IMAGE_WATER_CONFIG.size' => array(
		'name'    => '文字大小',
		'group'   => '水印设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1, 'max'=>100)),
		'default' => C('IMAGE_WATER_CONFIG.size'),
	),
	'IMAGE_WATER_CONFIG.color' => array(
		'name'    => '文字颜色',
		'group'   => '水印设置',
		'editor'  => 'color',
		'default' => C('IMAGE_WATER_CONFIG.color'),
	),
	
	/* 邮箱设置  */
	'EMAIL_CONFIG.smtp' => array(
		'name'    => 'SMTP',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'combobox','options'=>array('editable'=>true, 'multiple'=>false,'data'=>array(
			array('text'=>'smtp.163.com', 'value'=>'smtp.163.com'),
			array('text'=>'smtp.126.com', 'value'=>'smtp.126.com'),
			array('text'=>'smtp.yeah.net', 'value'=>'smtp.yeah.net'),
			array('text'=>'smtp.china.com', 'value'=>'smtp.china.com'),
			array('text'=>'smtp.netease.com', 'value'=>'smtp.netease.com'),
			array('text'=>'smtp.sina.com.cn', 'value'=>'smtp.sina.com.cn'),
			array('text'=>'smtp.sohu.com', 'value'=>'smtp.sohu.com'),
			array('text'=>'smtp.tom.com', 'value'=>'smtp.tom.com'),
			array('text'=>'smtp.qq.com', 'value'=>'smtp.qq.com'),
			array('text'=>'smtp.foxmail.com.cn', 'value'=>'smtp.foxmail.com.cn'),
			array('text'=>'smtp.gmail.com', 'value'=>'smtp.gmail.com'),
			array('text'=>'smtp.mail.yahoo.com', 'value'=>'smtp.mail.yahoo.com'),
			array('text'=>'smtp.ym.163.com', 'value'=>'smtp.ym.163.com'),
			array('text'=>'smtp.exmail.qq.com', 'value'=>'smtp.exmail.qq.com'),
		))),
		'default' => C('EMAIL_CONFIG.smtp'),
	),
	'EMAIL_CONFIG.port' => array(
		'name'    => '端口',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'numberspinner','options'=>array('min'=>1, 'max'=>10000)),
		'default' => C('EMAIL_CONFIG.port', null, 25),
	),
	'EMAIL_CONFIG.user' => array(
		'name'    => '用户名',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'validatebox','options'=>array('tipPosition'=>'left', 'validType'=>array('text','length[0,255]'))),
		'default' => C('EMAIL_CONFIG.user'),
	),
	'EMAIL_CONFIG.password' => array(
		'name'    => '密码',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'password','options'=>array('tipPosition'=>'left', 'validType'=>array('text','length[0,255]'))),
		'default' => C('EMAIL_CONFIG.password'),
	),
	'EMAIL_CONFIG.from' => array(
		'name'    => '发件人',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'validatebox','options'=>array('tipPosition'=>'left', 'validType'=>array('email','length[0,255]'))),
		'default' => C('EMAIL_CONFIG.from'),
	),
	'EMAIL_CONFIG.report' => array(
		'name'    => '接收报警邮箱',
		'group'   => '邮箱设置',
		'editor'  => array('type'=>'validatebox','options'=>array('tipPosition'=>'left', 'validType'=>array('email','length[0,255]'))),
		'default' => C('EMAIL_CONFIG.report'),
	),
);