<?php
return array(
	'text'=>array(//配置在表单中的键名 ,这个会是config[title]
		'title'=>'text类型:',//表单的文字
		'type'=>'text',		 //表单的类型：text、textarea、checkbox、radio、select等
		'value'=>'text默认值', //表单的默认值
	),
	'password'=>array(
		'title'=>'password类型:',
		'type'=>'password',
		'value'=>'password默认值',
	),
	'hidden'=>array(
		'title'=>'hidden类型:',
		'type'=>'hidden',
		'value'=>'hidden默认值',
	),
	'select'=>array(
		'title'=>'select类型:',
		'type'=>'select',
		'options'=>array(
			'1'=>'option1',
			'2'=>'option2',
			'4'=>'option3'
		),
		'value'=>'2'
	),
	'radio'=>array(
		'title'=>'radio类型:',
		'type'=>'radio',
		'options'=>array(
			'1'=>'显示',
			'0'=>'不显示'
		),
		'value'=>'0'
	),
	'checkbox'=>array(
		'title'=>'checkbox类型:',
		'type'=>'checkbox',
		'options'=>array(
			'1'=>'显示',
			'2'=>'不显示'
		),
		'value'=>'1,2'
	),
	'textarea'=>array(
		'title'=>'textarea类型:',
		'type'=>'textarea',
		'value'=>'textarea默认值'
	),
	'group'=>array(
		'type'=>'group',
		'options'=>array(
			'youyan'=>array(
				'title'=>'友言配置',
				'options'=>array(
					'comment_uid_youyan'=>array(
						'title'=>'账号id:',
						'type'=>'text',
						'value'=>'90040',
						'tip'=>'填写自己登录友言后的uid,填写后可进相应官方后台'
					),
				)
			),
			'duoshuo'=>array(
				'title'=>'多说配置',
				'options'=>array(
					'comment_short_name_duoshuo'=>array(
						'title'=>'短域名',
						'type'=>'text',
						'value'=>'',
						'tip'=>'每个站点一个域名'
					),
					'comment_form_pos_duoshuo'=>array(
						'title'=>'表单位置:',
						'type'=>'radio',
						'options'=>array(
							'top'=>'顶部',
							'buttom'=>'底部'
						),
						'value'=>'buttom'
					),
					'comment_data_list_duoshuo'=>array(
						'title'=>'单页显示评论数',
						'type'=>'text',
						'value'=>'10'
					),
					'comment_data_order_duoshuo'=>array(
						'title'=>'评论显示顺序',
						'type'=>'radio',
						'options'=>array(
							'asc'=>'从旧到新',
							'desc'=>'从新到旧'
						),
						'value'=>'asc'
					)
				)
			)
		)
	)
);
